# Generated by Django 6.0 on 2025-12-07 15:22

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Channel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('enabled', models.BooleanField(default=True)),
                ('input_type', models.CharField(choices=[('udp_multicast', 'UDP Multicast (MPEG-TS)'), ('rtsp', 'RTSP'), ('rtmp', 'RTMP'), ('file', 'File')], max_length=20)),
                ('input_url', models.CharField(help_text="For multicast: e.g. udp://@224.2.2.2:2001 (we'll add fifo_size & overrun options automatically).", max_length=512)),
                ('multicast_interface', models.CharField(blank=True, help_text='Optional: e.g. eth0. Leave blank to use system default.', max_length=64)),
                ('output_type', models.CharField(choices=[('hls', 'HLS (m3u8)'), ('rtmp', 'RTMP'), ('udp_ts', 'UDP TS Unicast'), ('file_ts', 'File (TS)'), ('file_mp4', 'File (MP4)')], max_length=20)),
                ('output_target', models.CharField(help_text='For HLS: directory path; for RTMP/UDP: URL (udp://ip:port, rtmp://...).', max_length=512)),
                ('record_enabled', models.BooleanField(default=True, help_text='If on, we are allowed to record this channel to disk.')),
                ('recording_path_template', models.CharField(default='/var/media/recordings/{channel}/{date}/', help_text='Use {channel}, {date}, {time} placeholders for folder path.', max_length=512)),
                ('recording_segment_minutes', models.PositiveIntegerField(default=60, help_text='Length of each recording segment in minutes.')),
                ('video_mode', models.CharField(choices=[('copy', 'Copy (no transcode)'), ('transcode', 'Transcode')], default='copy', max_length=16)),
                ('audio_mode', models.CharField(choices=[('copy', 'Copy (no transcode)'), ('transcode', 'Transcode'), ('disable', 'Disable audio')], default='copy', max_length=16)),
                ('video_codec', models.CharField(default='h264', help_text='Used only when transcoding (e.g. h264, hevc).', max_length=16)),
                ('audio_codec', models.CharField(default='aac', help_text='Used only when transcoding audio.', max_length=16)),
                ('hardware_preference', models.CharField(choices=[('auto', 'Auto (NVIDIA → Intel → CPU)'), ('nvidia', 'Force NVIDIA (if available)'), ('intel', 'Force Intel QSV (if available)'), ('cpu', 'Force CPU')], default='auto', help_text='AUTO = NVIDIA → Intel → CPU; or force one.', max_length=16)),
                ('target_width', models.PositiveIntegerField(blank=True, help_text='E.g. 1920. If null, keep source width.', null=True)),
                ('target_height', models.PositiveIntegerField(blank=True, help_text='E.g. 1080. If null, keep source height.', null=True)),
                ('video_bitrate', models.CharField(blank=True, help_text='E.g. 4000k. If blank, FFmpeg decides.', max_length=16)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
    ]
