# Generated by Django 6.0 on 2025-12-07 16:58

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transcoder', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='channel',
            name='recording_path_template',
            field=models.CharField(default='recordings/{channel}/{date}/', help_text='Path where recordings will be stored. Relative paths are under MEDIA_ROOT. Use {channel}, {date}, {time} placeholders.', max_length=512),
        ),
        migrations.CreateModel(
            name='Schedule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('purpose', models.CharField(choices=[('live_forward', 'Live forward'), ('record', 'Record')], default='live_forward', max_length=16)),
                ('enabled', models.BooleanField(default=True)),
                ('start_at', models.DateTimeField(help_text='When this job should start (server time).')),
                ('end_at', models.DateTimeField(help_text='When this job should stop (server time).')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('channel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='schedules', to='transcoder.channel')),
            ],
            options={
                'ordering': ['-start_at'],
            },
        ),
    ]
