# Generated by Django 6.0 on 2025-12-08 18:37

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transcoder', '0002_alter_channel_recording_path_template_schedule'),
    ]

    operations = [
        migrations.CreateModel(
            name='RecurringSchedule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('purpose', models.CharField(choices=[('live_forward', 'Live forward'), ('record', 'Record')], default='record', max_length=16)),
                ('enabled', models.BooleanField(default=True)),
                ('monday', models.BooleanField(default=True)),
                ('tuesday', models.BooleanField(default=True)),
                ('wednesday', models.BooleanField(default=True)),
                ('thursday', models.BooleanField(default=True)),
                ('friday', models.BooleanField(default=True)),
                ('saturday', models.BooleanField(default=True)),
                ('sunday', models.BooleanField(default=True)),
                ('start_time', models.TimeField(help_text='Local start time (HH:MM).')),
                ('end_time', models.TimeField(help_text='Local end time (HH:MM). Supports overnight windows like 20:00 → 06:00.')),
                ('date_from', models.DateField(blank=True, help_text='Optional: only apply from this date (inclusive).', null=True)),
                ('date_to', models.DateField(blank=True, help_text='Optional: only apply up to this date (inclusive).', null=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('channel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='recurring_schedules', to='transcoder.channel')),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='TimeShiftProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('enabled', models.BooleanField(default=False)),
                ('delay_minutes', models.PositiveIntegerField(default=180, help_text='Delay between live input and delayed output, in minutes (e.g. 180 = 3 hours).')),
                ('output_udp_url', models.CharField(help_text='UDP TS URL for delayed output, e.g. udp://239.0.0.10:2001', max_length=512)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('channel', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='timeshift_profile', to='transcoder.channel')),
            ],
            options={
                'verbose_name': 'Time-shift profile',
                'verbose_name_plural': 'Time-shift profiles',
            },
        ),
    ]
