# Generated by Django 6.0 on 2025-12-08 18:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transcoder', '0003_recurringschedule_timeshiftprofile'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recurringschedule',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='timeshiftprofile',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
