# Generated by Django 6.0 on 2025-12-08 19:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transcoder', '0004_alter_recurringschedule_created_at_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='channel',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='channel',
            name='recording_path_template',
            field=models.CharField(default='recordings/{channel}/{date}/', help_text='Recording path. Relative paths are under MEDIA_ROOT. Use {channel}, {date}, {time} placeholders.', max_length=512),
        ),
        migrations.AlterField(
            model_name='schedule',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='schedule',
            name='end_at',
            field=models.DateTimeField(help_text='When this job should stop (server/local time).'),
        ),
        migrations.AlterField(
            model_name='schedule',
            name='start_at',
            field=models.DateTimeField(help_text='When this job should start (server/local time).'),
        ),
    ]
