# Generated by Django 6.0 on 2025-12-10 10:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transcoder', '0005_alter_channel_created_at_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recurringschedule',
            name='end_time',
            field=models.TimeField(help_text='Local end time (HH:MM). If later than Start time, the schedule runs within the same day. If earlier than Start time, the schedule runs overnight. If Start time and End time are both set to 00:00, the schedule runs for the entire day.'),
        ),
        migrations.AlterField(
            model_name='recurringschedule',
            name='start_time',
            field=models.TimeField(help_text='Local start time (HH:MM). If Start time and End time are both set to 00:00, the schedule runs for the entire day.'),
        ),
    ]
