# Generated by Django 6.0 on 2025-12-10 10:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transcoder', '0006_alter_recurringschedule_end_time_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recurringschedule',
            name='purpose',
            field=models.CharField(choices=[('live_forward', 'Live forward'), ('record', 'Record'), ('playback', 'Playback (delayed)')], default='record', max_length=16),
        ),
        migrations.AlterField(
            model_name='schedule',
            name='purpose',
            field=models.CharField(choices=[('live_forward', 'Live forward'), ('record', 'Record'), ('playback', 'Playback (delayed)')], default='live_forward', max_length=16),
        ),
    ]
